#!/usr/bin/perl
# mkromfs.pl - Build and inspect RFS2 ROMFS images.
# Usage:
#   mkromfs.pl <src-dir> <output.romfs>
#   mkromfs.pl --list <image.romfs>
#   mkromfs.pl --carray <image.romfs> <output.c> <symbol-name>
use strict;
use warnings;
use File::Find;

use constant {
    MAGIC       => 'RFS2',
    HEADER_FMT  => 'a4 L',
    HEADER_SIZE => 8,
    ENTRY_FMT   => 'L L',
    ENTRY_SIZE  => 8,
    U32_MAX     => 0xffffffff,
};

sub a4 { ($_[0]+3)&~3 }
sub pad4 { "\0" x (a4($_[0])-$_[0]) }

sub list_romfs {
    my ($image)=@_;
    open my $fh,'<:raw',$image or die "open $image: $!\n";
    local $/;my $img=<$fh>;close $fh;
    length($img)>=HEADER_SIZE or die "$image: bad header\n";
    my ($magic,$total)=unpack(HEADER_FMT,substr($img,0,HEADER_SIZE));
    $magic eq MAGIC or die "$image: bad magic\n";
    $total==length($img) or die "$image: bad total_size\n";

    my ($p,@e)=(HEADER_SIZE);
    while($p<$total){
        $p+ENTRY_SIZE<=$total or die "$image: bad entry\n";
        my ($nl,$size)=unpack(ENTRY_FMT,substr($img,$p,ENTRY_SIZE));$p+=ENTRY_SIZE;
        $nl<$total-$p or die "$image: bad name\n";
        my $name=substr($img,$p,$nl);
        substr($img,$p+$nl,1) eq "\0" or die "$image: bad name terminator\n";
        $p=a4($p+$nl+1);$p<=$total or die "$image: bad name padding\n";
        my $off=$p;
        $size<$total-$p or die "$image: bad data\n";
        substr($img,$p+$size,1) eq "\0" or die "$image: bad data terminator\n";
        $p=a4($p+$size+1);$p<=$total or die "$image: bad data padding\n";
        push @e,[$name,$off,$size];
    }
    $p==$total or die "$image: bad image size\n";
    printf "magic=%s file_count=%d total_size=%d\n",$magic,scalar(@e),$total;
    printf "  %s offset=%d size=%d\n",@$_ for @e;
}

sub build_romfs {
    my ($srcdir,$outfile)=@_;
    -d $srcdir or die "$srcdir: not a directory\n";
    my @files;
    find({wanted=>sub{
        return unless -f $_;
        my $rel=$File::Find::name;$rel=~s{^\Q$srcdir\E/?}{};
        push @files,$rel;
    },no_chdir=>1},$srcdir);
    @files=sort @files;
    @files or die "$srcdir: no files found\n";

    my $body='';
    for my $rel (@files){
        open my $fh,'<:raw',"$srcdir/$rel" or die "open $srcdir/$rel: $!\n";
        local $/;my $data=<$fh>;close $fh;
        my ($nl,$size)=(length($rel),length($data));
        $nl<=U32_MAX or die "path too long for RFS2: $rel\n";
        $size<=U32_MAX or die "file too large for RFS2: $rel\n";
        $body.=pack(ENTRY_FMT,$nl,$size);
        $body.=$rel."\0".pad4($nl+1);
        $body.=$data."\0".pad4($size+1);
    }

    my $total=HEADER_SIZE+length($body);
    $total<=U32_MAX or die "ROMFS image too large\n";
    open my $out,'>:raw',$outfile or die "open $outfile: $!\n";
    print $out pack(HEADER_FMT,MAGIC,$total),$body;
    close $out;
    printf "wrote %s: %d files, %d bytes\n",$outfile,scalar(@files),$total;
}

sub build_carray {
    my ($image,$outfile,$symbol)=@_;
    open my $in,'<:raw',$image or die "open $image: $!\n";
    local $/;my $bytes=<$in>;close $in;
    open my $out,'>',$outfile or die "open $outfile: $!\n";
    print $out "/* generated by mkromfs.pl --carray; do not edit */\n";
    print $out "__attribute__((section(\".romfs\"), aligned(4)))\n";
    print $out "const unsigned char ${symbol}[] = {\n";
    my @b=unpack('C*',$bytes);
    while(@b){my @l=splice(@b,0,16);print $out "  ",join(',',@l),",\n";}
    print $out "};\nconst unsigned long ${symbol}_size=sizeof(${symbol});\n";
    close $out;
    printf "wrote %s: %d bytes as %s[]\n",$outfile,length($bytes),$symbol;
}

@ARGV or die
    "usage: $0 <src-dir> <output.romfs>\n".
    "       $0 --list <image.romfs>\n".
    "       $0 --carray <image.romfs> <output.c> <symbol-name>\n";

if($ARGV[0] eq '--list'){
    @ARGV==2 or die "usage: $0 --list <image.romfs>\n";
    list_romfs($ARGV[1]);
}elsif($ARGV[0] eq '--carray'){
    @ARGV==4 or die "usage: $0 --carray <image.romfs> <output.c> <symbol-name>\n";
    build_carray($ARGV[1],$ARGV[2],$ARGV[3]);
}else{
    @ARGV==2 or die "usage: $0 <src-dir> <output.romfs>\n";
    build_romfs($ARGV[0],$ARGV[1]);
}
