#!/usr/bin/perl
use strict;
use warnings;

my (%v,@order);
while(<DATA>){
    chomp;
    next if $_ eq '' || /^#/;
    /^([A-Za-z_]\w*)='.*'$/ or die "invalid config: $_\n";
    $v{$1}=$_;
    push @order,$1;
}
open my $in,'<','uconfig.sh' or die "uconfig.sh: $!\n";
open my $out,'>','uconfig.sh.pico2' or die "uconfig.sh.pico2: $!\n";
while(<$in>){
    if(/^([A-Za-z_]\w*)=/ && exists $v{$1}){
        print $out delete($v{$1}),"\n";
    }else{
        print $out $_;
    }
}
print $out "$v{$_}\n" for grep {exists $v{$_}} @order;
close $in;
close $out;

local $ENV{CONFIG_SH}='uconfig.sh.pico2';
local $ENV{CONFIG_H}='uconfig.h';

system('sh','config_h.SH')==0 or die "config_h.SH failed\n";
-f 'uconfig.h' or die "config_h.SH did not produce uconfig.h\n";

__DATA__
# Overrides for pristine Perl 5.12.5 uconfig.sh (not a standalone Configure).
# QEMU MPS2-AN505, Cortex-M33 hard-float, ILP32; no host Perl Config import.
archname='m33os-cortex-m33'
osname='m33os'
osvers='1'
alignbytes='8'
shortsize='2'
intsize='4'
longsize='4'
ptrsize='4'
sizesize='4'
longlongsize='8'
doublesize='8'
longdblsize='8'
doublekind='3'
byteorder='1234'
ivtype='long'
uvtype='unsigned long'
ivsize='4'
uvsize='4'
nvtype='float'
nvsize='4'
nv_preserves_uv_bits='24'
nv_overflows_integers_at='16777216.0F'
d_nv_preserves_uv='undef'
u8type='unsigned char'
i8type='signed char'
u16type='unsigned short'
i16type='short'
u32type='unsigned int'
i32type='int'
u32size='4'
i32size='4'
i64type='long long'
u64type='unsigned long long'
i64size='8'
u64size='8'
d_quad='define'
quadkind='3'
quadtype='long long'
uquadtype='unsigned long long'
use64bitint='undef'
use64bitall='undef'
uselongdouble='undef'
useperlio='undef'
usemymalloc='n'
usemultiplicity='undef'
useithreads='undef'
use5005threads='undef'
useshrplib='false'
usedl='undef'
useposix='false'
uidtype='unsigned int'
gidtype='unsigned int'
pidtype='int'
sizetype='size_t'
ssizetype='long'
fpostype='long'
fpossize='4'
lseektype='long'
lseeksize='4'
timetype='time_t'
signal_t='void'
privlib='lib'
privlibexp='lib'
archlib='lib'
archlibexp='lib'
sitelib=''
sitelibexp=''
sitearch=''
sitearchexp=''
vendorlib=''
vendorlibexp=''
siteprefix=''
sh='/bin/sh'
d_const='define'
d_volatile='define'
d_casti32='define'
d_castneg='define'
d_dbl_dig='define'
d_memchr='define'
d_memcmp='define'
d_memcpy='define'
d_memmove='define'
d_memset='define'
d_strchr='define'
d_strerror='define'
d_strtol='define'
d_strtoul='define'
d_strtod='undef'
d_vprintf='define'
d_vsprintf='define'
d_vsnprintf='define'
d_snprintf='define'
d_isnan='define'
d_isinf='define'
d_fgetpos='define'
d_fsetpos='define'
d_fdopen='define'
d_getcwd='define'
d_getenv='define'
d_difftime='undef'
d_times='undef'
d_gettimeofday='undef'
d_fork='undef'
d_vfork='undef'
d_pipe='undef'
d_waitpid='undef'
d_kill='undef'
d_sigaction='undef'
d_sigprocmask='undef'
d_sigsetjmp='undef'
d_readdir='undef'
d_closedir='undef'
d_seekdir='undef'
d_telldir='undef'
d_rewinddir='undef'
d_link='undef'
d_symlink='undef'
d_readlink='undef'
d_rename='undef'
d_mkdir='undef'
d_rmdir='undef'
d_chown='undef'
d_fchmod='undef'
d_fchown='undef'
d_flock='undef'
d_socket='undef'
d_sockpair='undef'
d_select='undef'
d_poll='undef'
d_getpgrp='undef'
d_setpgrp='undef'
d_setsid='undef'
d_uname='undef'
d_getpwent='undef'
d_getgrent='undef'
d_getpwnam='undef'
d_getpwuid='undef'
d_getgrnam='undef'
d_getgrgid='undef'
d_setlocale='undef'
d_nl_langinfo='undef'
d_locconv='undef'
d_localeconv_l='undef'
d_faststdio='undef'
d_stdio_cnt_lval='undef'
d_stdio_ptr_lval='undef'
d_stdio_ptr_lval_nochange_cnt='undef'
d_stdio_ptr_lval_sets_cnt='undef'
d_stdio_stream_array='undef'
d_stdstdio='undef'
d_gconvert='undef'
d_gcvt='undef'
d_sprintf_returns_strlen='define'
gconvert='sprintf((b),"%.*g",(n),(double)(x))'
drand01='((rand() & 0x7fff) / 32768.0F)'
randbits='31'
randfunc='rand'
randseedtype='unsigned int'
seedfunc='srand'
i_stddef='define'
i_stdarg='define'
i_stdlib='define'
i_string='define'
i_float='define'
i_limits='define'
i_inttypes='define'
i_unistd='define'
i_fcntl='define'
i_systypes='define'
i_sysstat='define'
i_syswait='define'
i_time='define'
i_dirent='define'
i_systime='undef'
i_systimes='undef'
i_syssocket='undef'
i_sysselect='undef'
i_sysioctl='undef'
i_sysfile='undef'
i_sysresource='undef'
i_sysutsname='undef'
i_sysmman='undef'
i_netdb='undef'
i_netinet_in='undef'
i_arpa_inet='undef'
i_pwd='undef'
i_grp='undef'
i_locale='undef'
i_langinfo='undef'
i_dlfcn='undef'
i_pthread='undef'
